language: php
php:
  - 7.2

before_script:
  - mkdir /usr/local/bin
  - curl -o /usr/local/bin/phpunit -L https://phar.phpunit.de/phpunit-7.phar
  - chmod +x /usr/local/bin/phpunit

script: phpunit --no-coverage